### ISSUE TITLE
Rest-client dependency in cloud backup library requires build-essentials

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/rackspace_cloudbackup#24]
While we were able to resolve https://github.com/rackspace-cookbooks/platformstack/issues/195 with a release/update, but this cookbook will still be broken.

**Comment by twistedgrim** [comment]
https://github.com/rackspace-cookbooks/rackspace_cloudbackup/pull/28

Holo..

Looks like some mistyping caused the fix to not actually fix.  PR is the real fix. Going to do rest_client instead of the more popular used rest-client.

https://github.com/rackspace-cookbooks/rackspace_cloudbackup/search?utf8=%E2%9C%93&q=rest_client

https://github.com/rackspace-cookbooks/rackspace_cloudbackup/commit/652dc04f8604056eae5249c33866dadba10da07b#diff-55bf87238c9b8af164c5133a60721f12R11

https://rubygems.org/gems/rest_client
vs
https://rubygems.org/gems/rest-client

**Comment by schwing** [comment]
Reopening for @twistedgrim and #28

**Comment by twistedgrim** [comment]
https://github.com/rackspace-cookbooks/rackspace_cloudbackup/issues/26

**Comment by martinb3** [comment]
See also https://github.com/AutomationSupport/chef-related-issues/issues/6 -- while rackspace_cloudbackup is fixed, platformstack doesn't include it correctly.
